### ARCHIVO DE PRUEBAS SIMULANDO LAS PETICIONES DEL FRONT
### INSTALA REST CLIENT EN VSCODE
### ABRE EL ARCHIVO DE NUEVO DESDE VSCODE Y PULSA EL BOTÓN "Send Request"

### REVISA (Y MODIFICA SI ES NECESARIO) QUE LA RUTA DEL POST COINCIDE CON LA CONFIGURACIÓN DE TU SERVIDOR LOCAL

### Guardar nueva puntuación
POST http://localhost/Hundir-la-flota/app/Models/save_score.php
Content-Type: application/json

{
  "name": "player1",
  "shots": 15
}
### Guardar nueva puntuación 2
POST http://localhost/Hundir-la-flota/app/Models/save_score.php
Content-Type: application/json

{
  "name": "player2",
  "shots": 20
}
### Intentar guardar sin datos (debe devolver error 400)
POST http://localhost/Hundir-la-flota/app/Models/save_score.php
Content-Type: application/json

{
  "name": "Player"
}

### Obtener el ranking actual
GET http://localhost/Hundir-la-flota/app/Models/get_score.php
